### PR TITLE
hoge

### PR DESCRIPTION
**Pull request by slazy**
@slazy

hoge

### CODE REVIEW

**Review by slazy — COMMENTED** [review]
HOGEHOGE

**Review by slazy — COMMENTED** [review]
@slazy
YES

**Comment by slazy** [comment]
> 
<sub>[View in Slack](https://reiga.slack.com/archives/D593EN20K/p1544799235001100)</sub>

TEST

**Comment by Zeale** [comment]
Hm?

**Comment by slazy** [comment]
i just had a mistake to mention. i'm sorry.

**Comment by Zeale** [comment]
Oh, it'z fine.

**Pull request merged**
